### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by karlarao** [t3rmin4t0r/lipwig#4]
I'm getting the following error using the HDP sandbox version 2.5

```
python --version
Python 2.7.5
hive --version
Hive 1.2.1000.2.5.0.0-1245
hadoop version
Hadoop 2.7.3.2.5.0.0-1245
```

```
[root@localhost lipwig-master]# python lipwig.py explain.json > explain.dot
Traceback (most recent call last):
  File "lipwig.py", line 252, in <module>
    main(sys.argv[1:])
  File "lipwig.py", line 248, in main
    p = [HivePlan(f, json.load(open(f))) for f in argv]
  File "lipwig.py", line 230, in __init__
    assert len(stages) == 1
AssertionError

```

Here's the explain.json file
```
{"STAGE DEPENDENCIES":{"Stage-0":{"ROOT STAGE":"TRUE"}},"STAGE PLANS":{"Stage-0":{"Fetch Operator":{"Processor Tree:":{"TableScan":{"alias:":"customer","children":{"Select Operator":{"children":{"Limit":{"children":{"ListSink":{}},"Number of rows:":"2"}},"outputColumnNames:":["_col0","_col1","_col2","_col3","_col4","_col5","_col6","_col7","_col8","_col9","_col10","_col11","_col12","_col13","_col14","_col15","_col16","_col17","_col18","_col19","_col20","_col21","_col22","_col23","_col24","_col25","_col26","_col27","_col28"],"expressions:":"customer_id (type: int), account_num (type: bigint), lname (type: varchar(30)), fname (type: varchar(30)), mi (type: varchar(30)), address1 (type: varchar(30)), address2 (type: varchar(30)), address3 (type: varchar(30)), address4 (type: varchar(30)), city (type: varchar(30)), state_province (type: varchar(30)), postal_code (type: varchar(30)), country (type: varchar(30)), customer_region_id (type: int), phone1 (type: varchar(30)), phone2 (type: varchar(30)), birthdate (type: date), marital_status (type: varchar(30)), yearly_income (type: varchar(30)), gender (type: varchar(30)), total_children (type: smallint), num_children_at_home (type: smallint), education (type: varchar(30)), date_accnt_opened (type: date), member_card (type: varchar(30)), occupation (type: varchar(30)), houseowner (type: varchar(30)), num_cars_owned (type: int), fullname (type: varchar(60))"}}}},"limit:":"2"}}}}
```

.

**Comment by bjernigan** [comment]
@karlarao I came across this same issue, but it looks like it was because I'm using MR and not Tez.

**Comment by yaravind** [comment]
Any plans to have this updated for Tez?
